
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange_default
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto : none
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  sql:
    init:
#      Ubicacion de scripts sql
      data-locations: classpath:db/migration/*.sql
#     Modo de inicializacion de base de datos (always, embedded, never)
      mode: always